name: Deploy AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Install pipx
        run: |
          python3.12 -m pip install --upgrade pip
          python3.12 -m pip install pipx --user
      
      - name: Install poetry
        run: |
          python3.12 -m pipx install poetry    
      
      - name: Install dependencies
        run: |
          poetry install
      
      - name: Test with pytest
        run: |
          poetry run pytest -s

      - name: Build ASGI app
        run: |
          python3.12 -m pip install -t dist/lambda .

      - name: Zip the lambda
        run: |
          cd dist/lambda
          zip -x '*.pyc' -r ../lambda.zip .
            
      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name sample_aws \
            --runtime python3.12.x \
            --handler sample_aws.handler.handler \
            --zip-file fileb://lambda.zip \ 
            --role arn:aws:iam::${{ secrets.AWS_LAMBDA_ROLE_PUBLISHER }}:role/lambda-publisher










